version: "3.9"

services:
  fultec_dash:
    image: fultec-dash:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8503:8501"   # host:container
    environment:
      FULTec_BASE_URL: "http://api.fueltec.com.br:30565/integracao/v1/"
      FULTec_TIMEOUT: "20"
      FULTec_USER: "${FULTec_USER}"
      FULTec_PASS: "${FULTec_PASS}"
      FULTec_CNPJ: "${FULTec_CNPJ}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
    restart: unless-stopped
